apiVersion: v1
kind: Service
metadata:
  name: fuseki-delta
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9116'
    prometheus.io/path: '/probe'
spec:
  type: NodePort
  ports:
    - name: fuseki-delta
      port: 3030
    - name: json-exporter
      port: 9116
