apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trinidata
commonLabels:
  app: fuseki-patchlog
configMapGenerator:
  - name: fuseki-patchlog-env
    env:  env.env
  - name: run-sh
    files: [ run.sh ]
  - name: log4j
    files: [ log4j2.xml ]
  - name: s3ini
    files: [ s3.ini ]
resources:
  - deploy.yml
  - svc.yml
